In [1]:
import numpy as np
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 7.01 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 499 ms


In [4]:
# The NumPy ndarray: A Multidimensional Array Object
data = np.random.randn(2,3)
data

array([[-0.20800247,  0.84917091,  1.56728145],
       [-0.98786172,  0.07274464,  0.01737682]])

In [5]:
data * 10

array([[-2.08002466,  8.49170908, 15.67281452],
       [-9.87861722,  0.72744637,  0.17376819]])

In [6]:
data + data

array([[-0.41600493,  1.69834182,  3.1345629 ],
       [-1.97572344,  0.14548927,  0.03475364]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int32')

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((2, 3, 2))

array([[[8.36531839e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.08221785e-312, 3.69920389e-057]],

       [[1.42382526e+160, 3.60036681e+175],
        [4.05314205e+174, 4.25234002e+174],
        [9.77054693e+165, 6.58988739e-066]]])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array     
asarray    
arange     
ones,     
ones_like     
zeros,     
zeros_like    
empty,      
empty_like      
zeros      
full,      
full_like      
eye, identity      

In [19]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [22]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [23]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [24]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [25]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [26]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [28]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [33]:
arr2 = np.array([[0.,4.,1.], [7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [34]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [35]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[5]

5

In [37]:
arr[5:8]

array([5, 6, 7])

In [38]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [39]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [40]:
arr_slice[1] =12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [41]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [42]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [43]:
arr2d[0][2]

3

In [44]:
arr2d[0,2]

3

In [45]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
old_values = arr3d[0].copy()
arr3d[0] =42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[1,0]

array([7, 8, 9])

In [49]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [50]:
x[0]

array([7, 8, 9])

In [51]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [52]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [53]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [56]:
arr2d[1, :2]

array([4, 5])

In [57]:
arr2d[:2, 2]

array([3, 6])

In [58]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [59]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [60]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [61]:
data

array([[ 1.83935468, -0.10756143,  0.55695502,  0.15020467],
       [-0.18881302, -0.42540199,  0.6641511 ,  0.37818448],
       [ 0.71936785, -0.69201625,  0.66436147,  0.00298672],
       [-0.19669028, -0.31102417, -0.95008569,  0.66861638],
       [ 0.86007048, -0.57435771, -0.0762893 , -0.64765231],
       [ 1.37146445,  1.01558821,  0.1710048 , -0.77372407],
       [-1.29561311,  0.144996  , -0.57845596,  0.14579803]])

In [62]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [63]:
data[names=='Bob']

array([[ 1.83935468, -0.10756143,  0.55695502,  0.15020467],
       [-0.19669028, -0.31102417, -0.95008569,  0.66861638]])

In [64]:
data[names == 'Bob', 2:]

array([[ 0.55695502,  0.15020467],
       [-0.95008569,  0.66861638]])

In [65]:
data[names == 'Bob', 3]

array([0.15020467, 0.66861638])

In [66]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [67]:
data[~(names=='Bob')]

array([[-0.18881302, -0.42540199,  0.6641511 ,  0.37818448],
       [ 0.71936785, -0.69201625,  0.66436147,  0.00298672],
       [ 0.86007048, -0.57435771, -0.0762893 , -0.64765231],
       [ 1.37146445,  1.01558821,  0.1710048 , -0.77372407],
       [-1.29561311,  0.144996  , -0.57845596,  0.14579803]])

In [68]:
cond = names == 'Bob'
data[~cond]

array([[-0.18881302, -0.42540199,  0.6641511 ,  0.37818448],
       [ 0.71936785, -0.69201625,  0.66436147,  0.00298672],
       [ 0.86007048, -0.57435771, -0.0762893 , -0.64765231],
       [ 1.37146445,  1.01558821,  0.1710048 , -0.77372407],
       [-1.29561311,  0.144996  , -0.57845596,  0.14579803]])

In [69]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [70]:
data[mask]

array([[ 1.83935468, -0.10756143,  0.55695502,  0.15020467],
       [ 0.71936785, -0.69201625,  0.66436147,  0.00298672],
       [-0.19669028, -0.31102417, -0.95008569,  0.66861638],
       [ 0.86007048, -0.57435771, -0.0762893 , -0.64765231]])

In [71]:
data[data<0] = 0
data

array([[1.83935468, 0.        , 0.55695502, 0.15020467],
       [0.        , 0.        , 0.6641511 , 0.37818448],
       [0.71936785, 0.        , 0.66436147, 0.00298672],
       [0.        , 0.        , 0.        , 0.66861638],
       [0.86007048, 0.        , 0.        , 0.        ],
       [1.37146445, 1.01558821, 0.1710048 , 0.        ],
       [0.        , 0.144996  , 0.        , 0.14579803]])

In [72]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.6641511 , 0.37818448],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.37146445, 1.01558821, 0.1710048 , 0.        ],
       [0.        , 0.144996  , 0.        , 0.14579803]])

In [73]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [74]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [75]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [76]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [77]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [78]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [79]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [81]:
arr = np.random.randn(6,3)
arr

array([[-0.98533392, -0.6176347 ,  0.05381637],
       [ 1.3421951 ,  0.44149083,  0.12619057],
       [ 0.85899703,  1.42541942,  0.2695906 ],
       [ 0.35429346, -0.5373408 ,  0.73050212],
       [ 0.12207397, -0.14436703,  0.34486219],
       [ 0.53951416,  0.98815261, -0.10351176]])

In [82]:
np.dot(arr.T, arr)

array([[ 3.94174798,  2.75069683,  0.59298755],
       [ 2.75069683,  3.89422985, -0.13784794],
       [ 0.59298755, -0.13784794,  0.75477731]])

In [83]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [84]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [85]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [86]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [87]:
# Universal Functions: Fast Element-Wise Array Functions
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [89]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [90]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-0.23560334, -0.1832196 , -0.35208022, -0.55573201, -0.27214165,
        0.38683103,  0.74172102, -0.25530575])

In [91]:
y

array([-0.05611928, -1.01244974, -1.00485603,  0.40949603,  2.08037215,
       -0.03798583, -0.03212795,  2.22595964])

In [92]:
np.maximum(x,y)

array([-0.05611928, -0.1832196 , -0.35208022,  0.40949603,  2.08037215,
        0.38683103,  0.74172102,  2.22595964])

In [93]:
arr = np.random.randn(7)*5
arr

array([10.44024437,  1.0377013 , -4.9509022 , -5.01851554, -0.80199188,
        5.34517167,  8.89455929])

In [94]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.44024437,  0.0377013 , -0.9509022 , -0.01851554, -0.80199188,
        0.34517167,  0.89455929])

In [95]:
whole_part

array([10.,  1., -4., -5., -0.,  5.,  8.])

In [96]:
arr

array([10.44024437,  1.0377013 , -4.9509022 , -5.01851554, -0.80199188,
        5.34517167,  8.89455929])

In [97]:
np.sqrt(arr)

array([3.2311367 , 1.01867625,        nan,        nan,        nan,
       2.31196273, 2.98237477])

In [98]:
np.sqrt(arr, arr)

array([3.2311367 , 1.01867625,        nan,        nan,        nan,
       2.31196273, 2.98237477])

In [99]:
arr

array([3.2311367 , 1.01867625,        nan,        nan,        nan,
       2.31196273, 2.98237477])

In [100]:
# Array-Oriented Programming with Arrays